[workspace]
members = ["user-daemon", "system-daemon", "u2fhid-protocol", "uhid-linux-sys", "uhid-linux-tokio", "uhid-linux-tokio/example", "u2f-core"]

[profile.release]
lto = true
panic = 'abort'
backtrace = false

[patch.crates-io]
systemd = { git = "https://github.com/danstiner/rust-systemd", branch = "bugfix/log-dependency-bound" }
