[package]
authors = ["Daniel Stiner <danstiner@gmail.com>"]
name = "u2f-core"
version = "0.2.0"
[dependencies]
assert_matches = "1.1.0"
base64 = "0.9.0"
byteorder = "1.1.0"
futures = "0.1.16"
lazy_static = "1.0.0"
openssl = "0.9.20"
quick-error = "1.2.1"
rand = "0.4.1"
rust-crypto = "0.2.36"
serde = "1.0.27"
serde_derive = "1.0.27"
slog = { version = "2.0.12", features = ["max_level_trace"] }
slog-stdlog = "3.0.2"
subtle = "0.3.0"
tokio-service = "0.1.0"
