[package]
authors = ["Daniel Stiner <danstiner@gmail.com>"]
name = "u2f-core"
version = "0.1.0"
[dependencies]
assert_matches = "1.1.0"
base64 = "0.7.0"
byteorder = "1.1.0"
futures = "0.1.16"
openssl = "0.9.20"
quick-error = "1.2.1"
rand = "0.3.17"
serde = "1.0.17"
serde_derive = "1.0.17"
slog = "2.0.12"
slog-stdlog = "3.0.2"
subtle = "0.3.0"
tokio-service = "0.1.0"

[dependencies.u2f-header]
path = "../u2f-header"
